# Generated by Django 4.2.4 on 2023-10-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Coloque um titulo para o vídeo. Esse titulo será visivel ao público', max_length=1000)),
                ('url', models.URLField(help_text='Coloque nesse campo a URL do vídeo fornecida pelo YouTube')),
                ('descricao', models.TextField(help_text='Coloque nesse campo uma descricao para o vídeo', max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'Videos',
                'db_table': 'Videos',
            },
        ),
    ]
