# Generated by Django 4.2.4 on 2023-10-21 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Preencha esse campo com o titulo da materias', max_length=100)),
                ('resumo', models.TextField(help_text='Preencha com o resumo da materias', max_length=2500)),
                ('autor', models.CharField(help_text='Nome do criador da materia', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Materias',
                'db_table': 'Materias',
            },
        ),
        migrations.AlterField(
            model_name='videos',
            name='titulo',
            field=models.CharField(help_text='Coloque um titulo para o vídeo. Esse titulo será visivel ao público', max_length=100),
        ),
        migrations.CreateModel(
            name='Conteudos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(help_text='Preencha com o texto da sua materia', max_length=2500)),
                ('imagem', models.ImageField(upload_to='images/% Y/% m/')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conteudos', to='controller.materias')),
            ],
        ),
    ]
