# Generated by Django 4.2.4 on 2023-10-22 18:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0002_materias_alter_videos_titulo_conteudos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conteudos',
            options={'verbose_name_plural': 'Conteudos'},
        ),
        migrations.AddField(
            model_name='videos',
            name='publicacao',
            field=models.DateField(default=datetime.date(2023, 10, 22)),
        ),
        migrations.AlterModelTable(
            name='conteudos',
            table='Conteudos',
        ),
    ]
