# Generated by Django 4.2.4 on 2023-10-22 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0003_alter_conteudos_options_videos_publicacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagensMaterias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legenda', models.CharField(help_text='Preencha com uma legenda para imagem', max_length=50)),
                ('fonte', models.CharField(help_text='Preencha com a Fonte da imagem', max_length=200)),
                ('imagem', models.ImageField(upload_to='images/% Y/% m/')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materia_imagens', to='controller.materias')),
            ],
        ),
        migrations.CreateModel(
            name='TextosMaterias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topico', models.CharField(help_text='Preencha com o nome do Tópico', max_length=50)),
                ('texto', models.TextField(help_text='Preencha com o texto da sua materia', max_length=3000)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materia_textos', to='controller.materias')),
            ],
            options={
                'verbose_name': 'Textos Materias',
                'verbose_name_plural': 'Textos Materias',
                'db_table': 'Textos Materias',
            },
        ),
        migrations.DeleteModel(
            name='Conteudos',
        ),
    ]
