# Generated by Django 4.2.4 on 2023-10-22 20:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0004_imagensmaterias_textosmaterias_delete_conteudos'),
    ]

    operations = [
        migrations.AddField(
            model_name='materias',
            name='publicacao',
            field=models.DateField(default=datetime.date(2023, 10, 22)),
        ),
    ]
