# Generated by Django 4.2.4 on 2023-10-22 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0005_materias_publicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagensmaterias',
            name='imagem',
            field=models.FileField(upload_to='images/% Y/% m/'),
        ),
    ]
