# Generated by Django 4.2.4 on 2023-10-22 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0006_alter_imagensmaterias_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagensmaterias',
            name='imagem',
            field=models.ImageField(upload_to='imagens/% Y/% m/'),
        ),
    ]
