# Generated by Django 4.2.4 on 2023-11-16 00:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0008_alter_imagensmaterias_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='capa',
            field=models.ImageField(default=None, upload_to='capas'),
        ),
        migrations.AlterField(
            model_name='materias',
            name='publicacao',
            field=models.DateField(default=datetime.date(2023, 11, 15)),
        ),
        migrations.AlterField(
            model_name='videos',
            name='publicacao',
            field=models.DateField(default=datetime.date(2023, 11, 15)),
        ),
    ]
