# Generated by Django 4.2.4 on 2023-12-10 01:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0009_videos_capa_alter_materias_publicacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materias',
            name='publicacao',
            field=models.DateField(default=datetime.date(2023, 12, 9)),
        ),
        migrations.AlterField(
            model_name='videos',
            name='publicacao',
            field=models.DateField(default=datetime.date(2023, 12, 9)),
        ),
    ]
