# Generated by Django 4.2.4 on 2023-12-18 01:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0010_alter_materias_publicacao_alter_videos_publicacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='materias',
            name='capa',
            field=models.ImageField(default=None, upload_to='capas'),
        ),
        migrations.AlterField(
            model_name='materias',
            name='publicacao',
            field=models.DateField(default=datetime.date(2023, 12, 17)),
        ),
        migrations.AlterField(
            model_name='videos',
            name='publicacao',
            field=models.DateField(default=datetime.date(2023, 12, 17)),
        ),
    ]
