# Generated by Django 4.2.4 on 2024-01-17 23:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0013_materias_capa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materias',
            name='publicacao',
            field=models.DateField(default=datetime.date(2024, 1, 17)),
        ),
        migrations.AlterField(
            model_name='videos',
            name='publicacao',
            field=models.DateField(default=datetime.date(2024, 1, 17)),
        ),
    ]
